### PR TITLE
Update to latest bulma framework and latest version of font awesome.

### PR DESCRIPTION
**Pull request by gregoryhammond**
Updated to latest version of bulma (framework) and font awesome and included SRI so people can be sure they are getting the correct version and not a version that has been mortified.

### CODE REVIEW

**Comment by helfi92** [comment]
@gregoryhammond Thanks for the pull-request :) Just one small nit. I think there's extra white-spaces. Do you mind pushing a commit removing them. That way the PR doesn't say `+136  -135`.

**Comment by gregoryhammond** [comment]
@helfi92 yep I'll do that right now.

**Comment by gregoryhammond** [comment]
@helfi92 that commit should do it, but I think the PR says `+136 -135` because many things got moved down a line (or two).

**Comment by gregoryhammond** [comment]
@helfi92 there should also be a license file in this repo if you want people to be able to create websites using this. I can either add it or you can (I suggest [Unlicense](https://unlicense.org/)).

**Comment by helfi92** [comment]
@gregoryhammond If you click on the last [commit](https://github.com/helfi92/studorlio/pull/5/commits/ca665ae13aee76c97a73b121749c1049c21c9783), you will see that the bulma css version was brought back to `0.3.1`.

Now if you head over to the "Files changed" tab, then append `?w=1` on the URL, you will see the diffs with whitespace ignored: [https://github.com/helfi92/studorlio/pull/5/files?w=1](https://github.com/helfi92/studorlio/pull/5/files?w=1). Since the last commit removed one of your changes, you will see this pull-request is only changing `font-awesome` version.

**Comment by helfi92** [comment]
For the license, there's [LICENSE](https://github.com/helfi92/studorlio/blob/master/LICENSE) currently sitting in the root directory :)

**Comment by helfi92** [comment]
@gregoryhammond Try doing what is being recommended [here](https://stackoverflow.com/a/28623244/6150432)

```
git rebase --whitespace=fix HEAD~
```

After that, you will need to force push your change.

**Comment by gregoryhammond** [comment]
@helfi92 removed white space, checked the differences.

**Comment by helfi92** [comment]
@gregoryhammond Do you think you can open a new pull-request with the same additions you wanted to put. I think this one is hard to clean since the old commits with the white-spaces are still here. I think having your changes is a great addition to the codebase, but we need to make sure those white-spaces are gone :)

**Comment by gregoryhammond** [comment]
Yep can do, I'll do that this afternoon.

**Comment by helfi92** [comment]
Awesome!

**Comment by gregoryhammond** [comment]
@helfi92 was just looking into doing another pull-request but saw it said 
> 136 additions and 135 deletions

and I know you don't want that . Saw we keep this or shall I make a new pull-request?

**Comment by helfi92** [comment]
@gregoryhammond I think that's because your master branch already has the 3 commits: https://github.com/gregoryhammond/studorlio/commits/master. Try deleting this repo, forking it again, then cloning it. That way, the 3 commits you already pushed yesterday will be removed:

```
* Tried to remove white space, everything may have moved due to SRI.
* Remove extra white space.
* Update to latest bulma framework and latest version of font awesome.
```

Once those commits are no longer here, you can proceed to create a pull-request. Hopefully the `136 additions 135 deletions` won't show again. If you're still having trouble, let me know and I'll try to help more :)

**Comment by gregoryhammond** [comment]
@helfi9 that doesn't work, it says 

> 135 additions and 135 deletions

I need to go and learn pull requests before doing another one. Thanks for your patience, and help.

**Comment by helfi92** [comment]
No worries. If you want to do things the recommended way, look into creating branches for a pull-request. In sum, the flow is usually like this:

```
git checkout -b update-versions
... // make your changes then proceed with the commands below
git add . // instead of putting a dot, you can just specify the files. Also, to see what files changed, you can do `git status`
git commit -m 'Added code to update versions'
git push origin update-versions
```

Then you can head over to your repo, and you will see a yellow banner asking you if you want to create a pull-request.

^ that's assuming you're using the terminal :p and not the git graphical interface :)

**Pull request closed without merging**
